apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  GATEWAY_HTTP_SERVER_HOST: "0.0.0.0"
  GATEWAY_HTTP_SERVER_PORT: "8080"
  GATEWAY_HTTP_SERVER_BACKLOG: "0"
  AUTH_SERVICE_HOST: "auth"
  AUTH_SERVICE_PORT: "5000"
  GROUP_SERVICE_HOST: "group"
  GROUP_SERVICE_PORT: "6000"
  BET_SERVICE_HOST: "bet"
  BET_SERVICE_PORT: "7000"
  GATEWAY_THREAD_POOL_CORE_SIZE: "8"
  GATEWAY_THREAD_POOL_MAX_SIZE: "20"
  GATEWAY_THREAD_POOL_KEEP_ALIVE: "30"
  JWT_REDIS_SLAVE_HOST: "twemproxy"
  JWT_REDIS_PORT: "6379"
  RL_HOST_0: "rate-limiter-0.rate-limiter"
  RL_HOST_1: "rate-limiter-1.rate-limiter"
  RL_HOST_2: "rate-limiter-2.rate-limiter"
  RL_HOST_3: "rate-limiter-3.rate-limiter"
  RL_HOST_4: "rate-limiter-4.rate-limiter"
  RL_HOST_5: "rate-limiter-5.rate-limiter"
  RL_PORT: "6379"
  RL_REQUEST_LIMIT: "500"
  RL_TIME_WINDOW: "60"
  FRONTEND_ADDR: "https://bettersquared.com:8080"
