apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-game-end-settle-bet-cronjob
spec:
  schedule: "0 */3 * * *" # 0 */3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-game-end-settle-bet
              image: bryanwsebaraj/update:1.0
              args: ["updateGameEndSettleBet"]
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: update-configmap
                - secretRef:
                    name: update-secret
          restartPolicy: OnFailure