apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bryanwsebaraj/auth:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret